
spring:
  application:
    name: order
  datasource:
    username: root
    password: w4247794
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.27.231.86/cloud_order?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  port: 8600
